[package]
name = "tre-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "tre_python"
crate-type = ["cdylib", "rlib"]

[dependencies]
ash = "0.38.0"
bytemuck = "1.25.2"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
raw-window-handle = "0.6.2"
tre-engine = { path = "../tre-engine" }
tre-platform = { path = "../tre-platform" }
tre-rhi-vulkan = { path = "../tre-rhi-vulkan" }
