/* Generated by cbindgen -- do not edit by hand. Regenerated on every `tre-ffi` build (see build.rs). */

#ifndef TRE_FFI_H
#define TRE_FFI_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum TreErrorCode {
    TRE_ERROR_CODE_SUCCESS = 0,
    TRE_ERROR_CODE_DEVICE_LOST,
    TRE_ERROR_CODE_SWAPCHAIN_OUT_OF_DATE,
    TRE_ERROR_CODE_PIPELINE_CREATION_FAILED,
    TRE_ERROR_CODE_INVALID_TEXTURE_DATA,
    TRE_ERROR_CODE_BINDLESS_ARRAY_EXHAUSTED,
    TRE_ERROR_CODE_TRANSIENT_POOL_BUDGET_EXCEEDED,
    TRE_ERROR_CODE_SHADER_COMPILATION_FAILED,
    /**
     * FFI-only: a shape-registry insert call was given a non-finite or
     * negative dimension. `tre_engine::shapes::ShapeRegistry::insert`
     * itself never fails (it always succeeds), so this crate's own
     * `tre_shape_registry_insert_*` wrappers validate before calling it
     * -- see `crate::registry`.
     */
    TRE_ERROR_CODE_INVALID_ARGUMENT,
    /**
     * FFI-only: [`crate::ffi_guard`] caught an unwinding Rust panic
     * before it could cross the C-ABI boundary (TECHNICAL.md Section
     * 9.4.1's "FFI safety" rule).
     */
    TRE_ERROR_CODE_PANIC_CAUGHT,
} TreErrorCode;

typedef enum TrePathCommandKind {
    TRE_PATH_COMMAND_KIND_MOVE_TO = 0,
    TRE_PATH_COMMAND_KIND_LINE_TO = 1,
    TRE_PATH_COMMAND_KIND_QUADRATIC_TO = 2,
    TRE_PATH_COMMAND_KIND_CUBIC_TO = 3,
    TRE_PATH_COMMAND_KIND_CLOSE = 4,
} TrePathCommandKind;

/**
 * Freed by [`tre_frame_buffer_free`], never by the caller's own
 * allocator (TECHNICAL.md Section 9.4.1's "memory ownership" rule:
 * Rust's allocator and the host language's allocator are never assumed
 * compatible).
 */
typedef struct TreFrameBuffer {
    const unsigned char *data;
    uintptr_t len;
    /**
     * The real backing allocation's own capacity, distinct from `len`
     * whenever the two differ -- `tre_frame_buffer_free` needs the
     * *exact* original capacity to reconstruct the `Vec<u8>` this leaked
     * (`Vec::from_raw_parts`'s own safety contract), and nothing about
     * `Vec<u8>` guarantees `capacity() == len()` even after
     * `shrink_to_fit` (the allocator is free to leave excess). A C
     * caller has no use for this field beyond passing the whole struct
     * back to `tre_frame_buffer_free` unchanged.
     */
    uintptr_t capacity;
} TreFrameBuffer;

typedef void *TreShapeRegistry;

typedef void *TreShapeId;

/**
 * One segment of a `Path`'s command list -- the `#[repr(C)]` tagged-
 * union shadow of `tre_engine::shapes::PathCommand` (TECHNICAL.md
 * Section 9.4.1: no Rust `enum`-with-data crosses the boundary
 * directly). Unused fields per `kind` are ignored on the Rust side and
 * should be zeroed by a well-behaved caller, but are never read for a
 * `kind` that doesn't name them.
 */
typedef struct TrePathCommand {
    enum TrePathCommandKind kind;
    /**
     * `MoveTo`/`LineTo`: the target point. `QuadraticTo`: the control
     * point. `CubicTo`: the first control point. `Close`: unused.
     */
    float x0;
    float y0;
    /**
     * `QuadraticTo`: the target point. `CubicTo`: the second control
     * point. Otherwise unused.
     */
    float x1;
    float y1;
    /**
     * `CubicTo`: the target point. Otherwise unused.
     */
    float x2;
    float y2;
} TrePathCommand;

typedef void *TreHeadlessRenderer;

/**
 * Packs 8-bit RGBA channels into the `u32` this crate's shape-insert
 * functions expect for a fill color -- the exact same byte order
 * `tre_engine::rgba8` produces (re-implemented here rather than
 * re-exported, since `tre_engine::rgba8` is a `const fn` returning a
 * plain `u32`, already trivially `extern "C"`-compatible, but not
 * itself marked `extern "C"`/`#[unsafe(no_mangle)]` -- this crate is the
 * one place that boundary-facing wrapping belongs, per its own module
 * doc comment above).
 */
uint32_t tre_rgba8(uint8_t r, uint8_t g, uint8_t b, uint8_t a);

/**
 * Frees a [`TreFrameBuffer`] returned by
 * [`crate::tre_headless_renderer_render`]. Safe to call on
 * [`TreFrameBuffer::empty`]'s own all-zero value (a no-op).
 *
 * # Safety
 * `buffer` must be a value this crate itself produced and not yet freed
 * -- calling this on a `TreFrameBuffer` built any other way, or calling
 * it twice on the same value, is undefined behavior (the same contract
 * every `tre_*_free` function in this crate carries).
 */
void tre_frame_buffer_free(struct TreFrameBuffer buffer);

/**
 * Creates a new, empty shape registry. Infallible.
 */
TreShapeRegistry tre_shape_registry_new(void);

/**
 * Destroys a registry created by [`tre_shape_registry_new`]. Safe to
 * call with a null/already-freed handle (a no-op).
 *
 * # Safety
 * `registry` must be null, or a still-live value [`tre_shape_registry_new`]
 * returned that has not already been freed. Any [`TreShapeId`] this
 * registry issued and not yet passed to [`tre_shape_registry_remove`]
 * or [`tre_shape_id_free`] is leaked, not use-after-freed -- `TreShapeId`
 * owns its own boxed `ShapeId` value independently of the registry.
 */
void tre_shape_registry_free(TreShapeRegistry registry);

/**
 * The number of shapes currently live in `registry`, or `0` if
 * `registry` is null.
 *
 * # Safety
 * `registry` must be null, or a still-live value [`tre_shape_registry_new`]
 * returned.
 */
uintptr_t tre_shape_registry_len(TreShapeRegistry registry);

/**
 * Inserts a solid-filled, borderless, corner-radius-free rectangle at
 * `(x, y)` (its own top-left corner) sized `width x height`, filled
 * `rgba` (see [`tre_rgba8`](crate::tre_rgba8)). Writes the new shape's
 * id to `*out_id`.
 *
 * # Errors
 * Returns [`TreErrorCode::InvalidArgument`] if `width`/`height` is
 * non-finite or negative, or `registry` is null.
 *
 * # Safety
 * `registry` must be a still-live value [`tre_shape_registry_new`]
 * returned. `out_id` must be valid for one write of a [`TreShapeId`],
 * or null (the id is discarded).
 */
enum TreErrorCode tre_shape_registry_insert_rectangle(TreShapeRegistry registry,
                                                      float x,
                                                      float y,
                                                      float width,
                                                      float height,
                                                      uint32_t rgba,
                                                      TreShapeId *out_id);

/**
 * Inserts a solid-filled, borderless, full (non-partial-arc) circle or
 * ellipse centered at `(x + radius_x, y + radius_y)` (`(x, y)` is its
 * own bounding-box top-left, matching [`tre_shape_registry_insert_rectangle`]'s
 * convention), filled `rgba`. Writes the new shape's id to `*out_id`.
 *
 * `radius_x == radius_y` is a circle; otherwise an ellipse.
 *
 * # Errors
 * Returns [`TreErrorCode::InvalidArgument`] if `radius_x`/`radius_y` is
 * non-finite or negative, or `registry` is null.
 *
 * # Safety
 * Same contract as [`tre_shape_registry_insert_rectangle`].
 */
enum TreErrorCode tre_shape_registry_insert_circle(TreShapeRegistry registry,
                                                   float x,
                                                   float y,
                                                   float radius_x,
                                                   float radius_y,
                                                   uint32_t rgba,
                                                   TreShapeId *out_id);

/**
 * Inserts a solid-filled, borderless regular `sides`-gon (not a star)
 * of `radius` centered at `(x, y)`, filled `rgba`. Writes the new
 * shape's id to `*out_id`.
 *
 * # Errors
 * Returns [`TreErrorCode::InvalidArgument`] if `radius` is non-finite
 * or negative, `sides` is less than 3, or `registry` is null.
 *
 * # Safety
 * Same contract as [`tre_shape_registry_insert_rectangle`].
 */
enum TreErrorCode tre_shape_registry_insert_polygon(TreShapeRegistry registry,
                                                    float x,
                                                    float y,
                                                    uint32_t sides,
                                                    float radius,
                                                    uint32_t rgba,
                                                    TreShapeId *out_id);

/**
 * Inserts a solid-filled, borderless path built from `commands`
 * (`count` entries), offset by `(x, y)`, filled `rgba`. Writes the new
 * shape's id to `*out_id`.
 *
 * # Errors
 * Returns [`TreErrorCode::InvalidArgument`] if `commands` is null while
 * `count` is non-zero, or `registry` is null.
 *
 * # Safety
 * Same contract as [`tre_shape_registry_insert_rectangle`], plus:
 * `commands` must be valid for reads of `count` consecutive
 * [`TrePathCommand`] values, or null if `count` is `0`.
 */
enum TreErrorCode tre_shape_registry_insert_path(TreShapeRegistry registry,
                                                 float x,
                                                 float y,
                                                 const struct TrePathCommand *commands,
                                                 uintptr_t count,
                                                 uint32_t rgba,
                                                 TreShapeId *out_id);

/**
 * Removes `id`'s shape from `registry`, freeing `id` itself in the same
 * call regardless of whether it was actually found (matching
 * `ShapeRegistry::remove`'s own "report, don't panic" contract for a
 * stale id) -- `id` must not be used again after this call.
 *
 * # Safety
 * `registry` must be a still-live value [`tre_shape_registry_new`]
 * returned. `id` must be null, or a still-live value this registry (or
 * any registry -- a foreign id is simply reported not-found, per
 * `ShapeRegistry::remove`'s own contract) issued, that has not already
 * been freed.
 */
bool tre_shape_registry_remove(TreShapeRegistry registry, TreShapeId id);

/**
 * Frees a [`TreShapeId`] without removing its shape from any registry
 * -- for a caller that created a shape and, for whatever reason, never
 * wants to remove it before the registry itself is destroyed (avoiding
 * a leak of the id's own tiny boxed allocation; the shape itself is
 * still reclaimed normally when the registry is freed).
 *
 * # Safety
 * `id` must be null, or a still-live value a `tre_shape_registry_insert_*`
 * call produced that has not already been passed to this function or to
 * [`tre_shape_registry_remove`].
 */
void tre_shape_id_free(TreShapeId id);

/**
 * Creates a headless (zero-window) renderer of `width x height`
 * pixels. Writes the new renderer's handle to `*out`.
 *
 * # Errors
 * Returns a real `TreErrorCode` (never panics across the boundary) if
 * the display-server connection, the probe window, or the underlying
 * Vulkan device/swapchain/pipeline setup fails -- see
 * `docs/getting-started.md`'s own disclosed caveat, inherited unchanged
 * here: this cannot render even headlessly in a true no-display
 * environment (a bare container with no compositor at all needs a
 * software Vulkan implementation plus a virtual display, the same way
 * this project's own CI does it).
 *
 * # Safety
 * `out` must be valid for one write of a [`TreHeadlessRenderer`].
 */
enum TreErrorCode tre_headless_renderer_new(uint32_t width,
                                            uint32_t height,
                                            TreHeadlessRenderer *out);

/**
 * Destroys a renderer created by [`tre_headless_renderer_new`]. Safe to
 * call with a null/already-freed handle (a no-op).
 *
 * # Safety
 * `renderer` must be null, or a still-live value
 * [`tre_headless_renderer_new`] wrote that has not already been freed.
 */
void tre_headless_renderer_free(TreHeadlessRenderer renderer);

/**
 * Renders every shape currently in `registry` and writes the resulting
 * raw BGRA8 pixel buffer (`width * height * 4` bytes) to `*out`. Always
 * flattens the entire registry (`ShapeRegistry::mark_all_dirty` runs
 * internally on every call) since there is no cross-language dirty-flag
 * protocol a caller on this side of the boundary could observe --
 * matching `tre-python`'s own identical, already-fixed-once convention
 * (REVIEW.md finding #196).
 *
 * # Errors
 * Returns a real `TreErrorCode` on ring-buffer starvation or a GPU
 * submission/device-loss failure. `*out` is left at
 * [`TreFrameBuffer::empty`] in that case, safe to pass to
 * [`tre_frame_buffer_free`](crate::tre_frame_buffer_free) unconditionally.
 *
 * # Safety
 * `renderer` and `registry` must each be a still-live value their
 * respective constructors produced. `out` must be valid for one write
 * of a [`TreFrameBuffer`].
 */
enum TreErrorCode tre_headless_renderer_render(TreHeadlessRenderer renderer,
                                               TreShapeRegistry registry,
                                               struct TreFrameBuffer *out);

#endif  /* TRE_FFI_H */
